In [1]:
import tensorflow as tf 
from tensorflow.keras import models, layers 
import matplotlib.pyplot as plt

In [3]:
IMAGE_SIZE = 256
BATCH_SIZE = 32

In [8]:
dataset = tf.keras.preprocessing.image_dataset_from_directory("Dataset", shuffle = "True", image_size = (IMAGE_SIZE, IMAGE_SIZE), batch_size = BATCH_SIZE)

Found 2152 files belonging to 3 classes.


In [10]:
class_names = dataset.class_names 
class_names 

['Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy']

In [11]:
len(dataset)

68

In [12]:
for image_batch, label_batch in dataset.take(1):
    print(image_batch[0])

tf.Tensor(
[[[153. 151. 165.]
  [162. 160. 174.]
  [158. 156. 170.]
  ...
  [114. 110. 124.]
  [115. 111. 125.]
  [121. 117. 131.]]

 [[145. 143. 157.]
  [154. 152. 166.]
  [152. 150. 164.]
  ...
  [116. 112. 126.]
  [115. 111. 125.]
  [118. 114. 128.]]

 [[149. 147. 161.]
  [156. 154. 168.]
  [154. 152. 166.]
  ...
  [122. 118. 132.]
  [120. 116. 130.]
  [118. 114. 128.]]

 ...

 [[142. 138. 152.]
  [143. 139. 153.]
  [139. 135. 149.]
  ...
  [121. 117. 131.]
  [121. 117. 131.]
  [126. 122. 136.]]

 [[140. 136. 150.]
  [142. 138. 152.]
  [137. 133. 147.]
  ...
  [113. 109. 123.]
  [114. 110. 124.]
  [122. 118. 132.]]

 [[138. 134. 148.]
  [143. 139. 153.]
  [142. 138. 152.]
  ...
  [106. 102. 116.]
  [108. 104. 118.]
  [118. 114. 128.]]], shape=(256, 256, 3), dtype=float32)


In [14]:
for image_batch, label_batch in dataset.take(1):
    print(image_batch[0].shape)

(256, 256, 3)
